// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqsxvkdizhelwcijuut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcXN4dmtkaXpoZWx3Y2lqdXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTI5OTQsImV4cCI6MjA1OTU4ODk5NH0.XwUzCZltDGfKqJg9wTVQARdh1ux6710pxUcdQVNiM3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);